name = "json_canvas_example"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
json_canvas = { path = "./json_canvas" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
